name: asc_portfolio
description: aladin_study_cafe_portfolio


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.13
  timer_builder: ^2.0.0
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  http: ^0.13.5
  dio: ^4.0.6
  flutter_secure_storage: ^6.0.0
  jwt_decoder: ^2.0.1
  equatable: ^2.0.5
  bootpay: ^4.4.2
  flutter_form_builder: ^7.7.0
  toast: ^0.3.0
  url_launcher: ^6.1.7



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

fonts:
  - family: Jalnan
    fonts:
      - assets: assets/font/Jalnan/JalnanOTF.otf

